//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMRS_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCategory
    {
        public int ID { get; set; }
        public int DataID { get; set; }
        public int CategoryID { get; set; }
        public string CategoryDesc { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Data Data { get; set; }
    }
}
