//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMRS_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int SN { get; set; }
        public string Name { get; set; }
        public int id { get; set; }
        public string category { get; set; }
        public string catDesc { get; set; }
        public Nullable<int> startYear { get; set; }
        public Nullable<int> endYear { get; set; }
        public string reportType { get; set; }
        public Nullable<int> year { get; set; }
        public string typeDesc { get; set; }
    }
}
